name: package
on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

jobs:
  passwdpot:
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Build Arch Linux package
        uses: FFY00/build-arch-package@v1
        with:
          PKGBUILD: PKGBUILD
